/* eslint-disable @typescript-eslint/naming-convention */

export const assets = {
    images: {
        'game/A.png': require('../assets/images/game/A.png').default,
        'game/B.png': require('../assets/images/game/B.png').default,
        'game/C.png': require('../assets/images/game/C.png').default,
        'game/D.png': require('../assets/images/game/D.png').default,
        'game/E.png': require('../assets/images/game/E.png').default,
        'game/F.png': require('../assets/images/game/F.png').default,
        'game/G.png': require('../assets/images/game/G.png').default,
        'game/H.png': require('../assets/images/game/H.png').default,
        'game/I.png': require('../assets/images/game/I.png').default,
        'game/J.png': require('../assets/images/game/J.png').default,
        'game/K.png': require('../assets/images/game/K.png').default,
        'game/L.png': require('../assets/images/game/L.png').default,
        'game/M.png': require('../assets/images/game/M.png').default,
        'game/N.png': require('../assets/images/game/N.png').default,
        'game/O.png': require('../assets/images/game/O.png').default,
        'game/P.png': require('../assets/images/game/P.png').default,
        'game/Q.png': require('../assets/images/game/Q.png').default,
        'game/R.png': require('../assets/images/game/R.png').default,
        'game/S.png': require('../assets/images/game/S.png').default,
        'game/T.png': require('../assets/images/game/T.png').default,
        'game/U.png': require('../assets/images/game/U.png').default,
        'game/V.png': require('../assets/images/game/V.png').default,
        'game/W.png': require('../assets/images/game/W.png').default,
        'game/X.png': require('../assets/images/game/X.png').default,
        'game/Y.png': require('../assets/images/game/Y.png').default,
        'game/Z.png': require('../assets/images/game/Z.png').default,
        'game/bkg.jpg': require('../assets/images/game/bkg.jpg').default,
        'game/hand.png': require('../assets/images/game/hand.png').default,
    },
    particles: {},
    sounds: {},
    spines: {},
    atlases: {},
};

export const Images = {
    'game/A': 'game/A.png',
    'game/B': 'game/B.png',
    'game/C': 'game/C.png',
    'game/D': 'game/D.png',
    'game/E': 'game/E.png',
    'game/F': 'game/F.png',
    'game/G': 'game/G.png',
    'game/H': 'game/H.png',
    'game/I': 'game/I.png',
    'game/J': 'game/J.png',
    'game/K': 'game/K.png',
    'game/L': 'game/L.png',
    'game/M': 'game/M.png',
    'game/N': 'game/N.png',
    'game/O': 'game/O.png',
    'game/P': 'game/P.png',
    'game/Q': 'game/Q.png',
    'game/R': 'game/R.png',
    'game/S': 'game/S.png',
    'game/T': 'game/T.png',
    'game/U': 'game/U.png',
    'game/V': 'game/V.png',
    'game/W': 'game/W.png',
    'game/X': 'game/X.png',
    'game/Y': 'game/Y.png',
    'game/Z': 'game/Z.png',
    'game/bkg': 'game/bkg.jpg',
    'game/hand': 'game/hand.png',
};

export const Sounds = {};

export const Particles = {};

export const Spines = {};
